apiVersion: v1
kind: ActionBoard
metadata:
  name: actors-board
  knowledge-graph: movies-kg
spec:
  label: 'Actors Board'
  template: 'file://actors-board-template.html'
  scope: GLOBAL
  perspective: main-perspective
  format: 2