apiVersion: v1
kind: ActionBoard
metadata:
  name: movie-action-board
  knowledge-graph: movies-kg
spec:
  label: 'Movies Action Board'
  template: 'file://movie-action-board-template.html'
  scope: GLOBAL
  perspective: main-perspective
  format: 2