apiVersion: v1
kind: ActionBoard
metadata:
  name: movie-action-board-v2
  knowledge-graph: movies-kg
spec:
  label: 'Movies Action Board v2'
  template: 'file://movie-action-board-template-v2.html'
  scope: GLOBAL
  perspective: main-perspective
  format: 2