apiVersion: v1
kind: Secret
metadata:
  name: orchestra-webhook-auth-header-secret
spec:
  access:
    - role: ANALYST
      permissionGroup: ECOSYSTEM_VARIABLE_KEY_USE
    - role: DRONE_TEAM
      permissionGroup: ECOSYSTEM_VARIABLE_KEY_USE
  key: ORCHESTRA_WEBHOOK_AUTH_HEADER
  value: Basic b3JjaGVzdHJhOm9yY2hlc3RyYQ==