apiVersion: v1
kind: UploadConfiguration
metadata: {}
spec:
  name: "DEFAULT"
  description: "The default upload configuration"
  # fileExtensions: []
  # maxFileSizeInBytes: 10485760
  # archived: false