apiVersion: v1
kind: Action
metadata:
  name: ab-test-table
  knowledge-graph: movies-kg
  tags:
    - all
spec:
  label: 'ab-test-table'
  query: 'file://test-action-table-cypher.cypher'
  scope: UTILITY
  returnType: TABLE
  inputParameters: []
