apiVersion: v1
kind: ActionBoard
metadata:
  name: movie-action-board-v2
  knowledge-graph: movies-kg
spec:
  label: 'Test Action Board'
  template: 'file://ab-test-template.html'
  scope: GLOBAL
  perspective: main-perspective
  format: 2