apiVersion: v1
kind: AlertingPattern
metadata:
  name: all-persons-pattern-weekly
  knowledge-graph: movies-kg
  includeIf:
    activeProfilesContainsAny:
      - alerting
spec:
  label: 'All Persons Pattern - Weekly'
  query: |
    MATCH (n:Person)
    RETURN id(n) AS key, n AS data
  conditions: ['NEW_RECORDS', 'DIFFERENT_RECORDS', 'DELETED_RECORDS']
  schedule:
    repetitionType: 'WEEKLY'
    executionTime: '15:30'
    executionDays: ['TUESDAY', 'WEDNESDAY']
    timeZone: 'UTC'
  perspective: main-perspective
  resource: neo4j-movies