apiVersion: v1
kind: EcosystemResource
metadata:
  name: minio-local-testbucket
spec:
  access: []
  fqn: Hume.Orchestra.Resource.Minio
  parameters:
    - name: host
      value: http://minio:9000
    - name: region
      value: us-east-1
    - name: bucket
      value: testbucket
    - name: access_key_id
      value: testuser
    - name: access_key_secret
      value: testpassword