apiVersion: v1
kind: EcosystemResource
metadata:
  name: neo4j-movies
spec:
  access:
    - role: ANALYST
      permissionGroup: RESOURCE_USE
    - role: DRONE_TEAM
      permissionGroup: RESOURCE_USE
  fqn: Hume.Orchestra.Resource.Neo4j
  parameters:
    - name: host
      value: neo4j
    - name: port
      value: 7687
    - name: user
      value: neo4j
    - name: password
      value: hellopassword
    - name: database
      value: movies