apiVersion: v1
kind: ValueList
metadata:
  name: firearm-manufacturers-vl
  knowledge-graph: movies-kg
spec:
  label: Firearm Manufacturers
  type: STRING
  seedUri: 'file://firearm-manufacturers-vl.csv'