apiVersion: v1
kind: AlertingCollection
metadata:
  name: actors-named-tom
  knowledge-graph: movies-kg
  includeIf:
    activeProfilesContainsAny:
      - alerting
spec:
  label: 'Actors named Tom'
  perspective: 'main-perspective'
  items:
    - id: 'tom-hanks'
      attributes:
        name: 'Tom Hanks'
    - id: 'tom-cruise'
      attributes:
        name: 'Tom Cruise'