apiVersion: v1
kind: AlertingPattern
metadata:
  name: pattern-with-params-2
  knowledge-graph: movies-kg
  includeIf:
    activeProfilesContainsAny:
      - alerting
spec:
  label: 'Pattern with Parameters 2'
  query: |
    MATCH (n:Person)
    WHERE n.name = $name
    RETURN id(n) AS key, n AS data
  parameters:
    - name: name
      type: STRING
  conditions: ['NEW_RECORDS', 'DIFFERENT_RECORDS', 'DELETED_RECORDS']
  schedule:
    repetitionType: 'FIXED'
    frequency: '30'
    frequencyUnit: 'SECONDS'
  perspective: main-perspective
  resource: neo4j-movies