apiVersion: v1
kind: Action
metadata:
  name: movies-wikipedia-search
  knowledge-graph: movies-kg
  tags:
    - all
spec:
  label: 'Movie Wikipedia Search'
  query: |
    MATCH (movie:Movie)
    WHERE movie.title = $movie
    WITH apoc.text.format('https://en.wikipedia.org/wiki/Special:Search?search=%s', [apoc.text.urlencode(movie.title)]) AS url
    RETURN '<iframe style="width: 100%; height: 1000px;" allowfullscreen frameborder="0" src="' + url + '" />' AS html
  scope: GLOBAL
  returnType: HTML
  inputParameters:
    - name: movie
      label: Movie
      type: STRING
      required: true