apiVersion: v1
kind: Action
metadata:
  name: movies-show-matrix-wikipedia-page
  knowledge-graph: movies-kg
  tags:
    - all
spec:
  label: 'Show Matrix Wikipedia Page'
  query: |
    RETURN '<iframe style="width: 100%; height: 100%;" frameborder="0" src="https://en.wikipedia.org/wiki/The_Matrix" />' AS html
  scope: UTILITY
  returnType: HTML