apiVersion: v1
kind: Action
metadata:
  name: resolvers-example
  knowledge-graph: movies-kg
  tags:
    - all
spec:
  label: 'Resolvers Example'
  query: |
    MATCH (n:Person) 
    WHERE elementId(n) = $selectedPerson
    RETURN n{.*} AS __row__
  scope: UTILITY
  returnType: TABLE
  defaultValuesResolver:
    type: CYPHER
    params:
      query: |
        MATCH (n:Person)
        WHERE n.name = 'Keanu Reeves'
        RETURN {id: elementId(n), value: n.name} AS selectedPerson
  inputParameters:
    - name: selectedPerson
      label: Selected Person
      type: SELECT_ASYNC
      resolver:
        type: CYPHER
      query: |
          MATCH (n:Person)
          WHERE toLower(n.name) CONTAINS toLower($selectedPerson)
          RETURN elementId(n) AS id, n.name AS value