apiVersion: v1
kind: Action
metadata:
  name: debug-context-variables
  knowledge-graph: movies-kg
  tags:
    - all
spec:
  label: 'debug context variables'
  query: |
    RETURN $_context.variables AS __kvRow__
  scope: UTILITY
  returnType: TABLE