apiVersion: v1
kind: Action
metadata:
  name: multiselected-nodes-table
  knowledge-graph: movies-kg
  tags:
    - all
spec:
  label: 'Multiselected Nodes Info As Table'
  query: |
    MATCH (n)
    WHERE elementId(n) IN $_selection.nodeElementIds
    RETURN n{.*} AS data
  inclusions:
    labels: ['*']
  scope: MULTISELECTION
  returnType: TABLE