apiVersion: v1
kind: Perspective
metadata:
  name: main-perspective
  knowledge-graph: lea.wicked-kg
spec:
  label: Main Perspective
  access:
    - role: ANALYST
      permissionGroup: PERSPECTIVE_USE
    - role: INVESTIGATOR
      permissionGroup: PERSPECTIVE_USE
  resourceName: neo4j-lea.wicked
  synced: true
  visibility:
    actions:
      - tag@all
      