apiVersion: v1
kind: Workflow
metadata:
  name: workflow-neo4j-basic
  knowledge-graph: movies-kg
spec:
  label: 'Workflow Neo4j Basic'
  # autostart: true
  components:
    - name: Stream Person nodes
      type: Neo4jStreamReader
      config:
        query: MATCH (n:Person) RETURN n AS data
        polling_period: 3000
      resourceName: neo4j-movies
      to:
        - MessageTransformer
    - name: MessageTransformer
      type: Transformer
      config:
        transformer_script: |
          body['source'] = 'neo4j-movies'

          return body
      to:
        - name: Observer
          disabled: false
        - name: Observer2
          disabled: true
    - name: Observer
      type: "#Hume.Orchestra.Monitor.Observer"
    - name: Observer2
      type: "#Hume.Orchestra.Monitor.Observer"
