events {
  worker_connections 1024;
}

http {

  client_max_body_size 20000M;

  # Use Docker's internal DNS
  # necessary to not cache dns entries for too long, otherwise if you restart media service
  # then the reverse proxy might have issues retrieving the correct ip.
  resolver 127.0.0.11 valid=10s;

  upstream media_upstream {
        zone media_zone 64k;
        server media:8008 resolve;
    }

  server {
    listen 80;

    # Allow /v1/download
    location /v1/download {
      proxy_pass http://media_upstream/v1/download;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Allow /v1/upload
    location /v1/upload {
      proxy_pass http://media_upstream/v1/upload;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Block all other routes
    location / {
      return 403;
    }
  }
}
