apiVersion: v1
kind: KnowledgeGraph
metadata:
  name: gold-kg
  knowledge-graph: gold-kg
spec:
  label: Gold KG
  access:
    strict: true
    rules: []
  perspectives:
    - main-perspective
  workflows: []
  actions: []
  settings:
    - name: visualisationGeospatialEnabled
      value: true
    - name: visualisationGroupingEnabled
      value: true
    - name: visualisationTemporalEnabled
      value: true
    - name: dataRefreshEnabled
      value: true
    - name: schemaStatisticsEnabled
      value: true
    - name: mdeEnabled
      value: false
  schema:
    strict: true
    classes:
      - label: License
        icon: mdi-card-account-details-outline
        color: '#F45D79'
        attributes:
        - {label: eyeColor, type: STRING, full_text: false, unique: false, list: false}
        - {label: age, type: INTEGER, full_text: false, unique: false, list: false}
        - {label: gender, type: STRING, full_text: false, unique: false, list: false}
        - {label: licenseNo, type: FLOAT, full_text: false, unique: false, list: false}
        - {label: hairColor, type: STRING, full_text: false, unique: false, list: false}
        - {label: height, type: INTEGER, full_text: false, unique: false, list: false}
      - label: GetFitNowCheckIn
        icon: event_available
        color: '#00A91C'
        attributes:
        - {label: date, type: STRING, full_text: false, unique: false, list: false}
      - label: FacebookEvent
        icon: mdi-facebook
        color: '#005EA2'
        attributes:
        - {label: eventId, type: INTEGER, full_text: false, unique: true, list: false}
        - {label: date, type: DATE, full_text: false, unique: false, list: false}
        - {label: eventName, type: STRING, full_text: true, unique: false, list: false}
      - label: GetFitNow
        icon: mdi-ticket-confirmation
        color: '#783CB9'
        attributes:
        - {label: status, type: STRING, full_text: false, unique: false, list: false}
        - {label: id, type: STRING, full_text: false, unique: true, list: false}
        - {label: startDate, type: DATE, full_text: false, unique: false, list: false}
      - label: Vehicle
        icon: mdi-car-hatchback
        color: '#B21D38'
        attributes:
        - {label: plateNumber, type: STRING, full_text: true, unique: false, list: false}
        - {label: carMake, type: STRING, full_text: true, unique: false, list: false}
        - {label: carModel, type: STRING, full_text: true, unique: false, list: false}
      - label: Interview
        icon: record_voice_over
        color: '#FD4496'
        attributes:
        - {label: transcript, type: STRING, full_text: true, unique: false, list: false}
      - label: CrimeSceneReport
        icon: mdi-file-document-outline
        color: '#FF8566'
        attributes:
        - {label: date, type: DATE, full_text: false, unique: false, list: false}
        - {label: description, type: STRING, full_text: true, unique: false, list: false}
        - {label: city, type: STRING, full_text: true, unique: false, list: false}
        - {label: type, type: STRING, full_text: true, unique: false, list: false}
      - label: Person
        icon: person
        color: '#2491FF'
        attributes:
        - {label: ssn, type: FLOAT, full_text: false, unique: true, list: false}
        - {label: id, type: STRING, full_text: false, unique: true, list: false}
        - {label: name, type: STRING, full_text: true, unique: false, list: false}
        - {label: addressStreet, type: STRING, full_text: true, unique: false, list: false}
        - {label: addressNumber, type: INTEGER, full_text: false, unique: false, list: false}
    relationships:
      - label: GAVE
        start: Person
        end: Interview
        attributes: []
      - label: HAS_LICENSE
        start: Person
        end: License
        attributes: []
      - label: CHECKED_IN_GYM
        start: GetFitNow
        end: GetFitNowCheckIn
        attributes: []
      - label: CHECKED_IN_EVENT
        start: Person
        end: FacebookEvent
        attributes: []
      - label: DRIVES
        start: Person
        end: Vehicle
        attributes: []
      - label: HAS_MEMBERSHIP
        start: Person
        end: GetFitNow
        attributes: []
