imports:
  - ./resources
  - ./secrets
  - ./variables
  - ./datasources
  - ./movies
removeOtherRoles: false
removeOtherResources: false
removeOtherPermissionGroups: false
roles:
  - name: ANALYST
  - name: INVESTIGATOR
  - name: SPINE_ANALYST