apiVersion: v1
kind: KnowledgeGraph
metadata:
  name: mde-kg
  knowledge-graph: mde-kg
spec:
  label: MDE KG
  access:
    strict: true
    rules:
      - role: INVESTIGATOR
        permissionGroup: MANAGER
      - role: ANALYST
        permissionGroup: EXPLORER
  perspectives:
    - main-perspective
    - vrel-perspective
  workflows: []
  actions: []
  settings:
    - name: visualisationGeospatialEnabled
      value: true
    - name: visualisationGroupingEnabled
      value: true
    - name: visualisationTemporalEnabled
      value: true
    - name: dataRefreshEnabled
      value: true
    - name: schemaStatisticsEnabled
      value: true
    - name: mdeEnabled
      value: true
    - name: accessControlEnabled
      value: true
    - name: editDeleteOnlyDataCreatedViaHume
      value: true
  schema:
    strict: true
    identity:
      identityAttribute: id
      classIdentityTemplate: '$uuid'
      relationshipIdentityTemplate: '$uuid'
    classes:
      - label: Person
        color: '#26A69A'
        icon: person
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: name
            type: STRING
            full_text: true
          - label: passportNumbers
            type: INTEGER
            list: true
      - label: Hotel
        color: '#3949AB'
        icon: mdi-warehouse
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: name
            type: STRING
            full_text: true
          - label: stars
            type: INTEGER
          - label: desc
            type: LARGE_TEXT
            full_text: true
      - label: Suspect
        color: '#37474F'
        icon: mdi-ninja
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: name
            type: STRING
            full_text: true
          - label: description
            type: LARGE_TEXT
          - label: bankBalance
            type: FLOAT
          - label: lastSeen
            type: GEOSPATIAL
          - label: Active
            type: NODE_LABEL
          - label: convicted
            type: BOOLEAN
          - label: hairColour
            type: STRING
            list: true
          - label: threatLevel
            type: INTEGER
          - label: lastUpdated
            type: DATE
      - label: Country
        color: '#FFC107'
        icon: mdi-google-maps
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: name
            type: STRING
            full_text: true
          - label: code
            type: STRING
      - label: AnotherThing
        color: '#BE32D0'
        attributes:
          - label: id
            type: STRING
            unique: true
      - label: YetAnotherThing
        color: '#005EA2'
        icon: mdi-hand-left
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: someStuff
            type: LARGE_TEXT
      - label: Place
        color: '#E91E63'
        icon: place
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: name
            type: STRING
            full_text: true
    relationships:
      - label: STAYS_AT
        start: Person
        end: Hotel
        attributes:
          - label: id
            type: STRING
            unique: true
            position: 0
          - label: from
            type: DATE
            position: 10
          - label: to
            type: DATE
            position: 20
          - label: roomType
            type: STRING
            position: 30
      - label: CITIZEN_OF
        start: Person
        end: Place
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: natural
            type: BOOLEAN
      - label: TRAVELS_TO
        start: Person
        end: Place
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: mode
            type: STRING
          - label: reason
            type: STRING
      - label: SEEN_AT
        start: Suspect
        end: Place
        attributes:
          - label: id
            type: STRING
            unique: true
      - label: IN_COUNTRY
        start: Place
        end: Country
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: annexed
            type: BOOLEAN
      - label: EMPLOYS
        start: Hotel
        end: Person
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: sinceYear
            type: INTEGER
      - label: DID
        start: Suspect
        end: AnotherThing
        attributes:
          - label: id
            type: STRING
            unique: true
      - label: CONQUERED
        start: Country
        end: Country
        attributes:
          - label: id
            type: STRING
            unique: true
          - label: year
            type: FLOAT
      - label: LOCATED_IN
        start: Hotel
        end: Place
        attributes:
          - label: id
            type: STRING
            unique: true