apiVersion: v1
kind: Workflow
metadata:
  name: workflow-event-store-listener
  knowledge-graph: mde-kg
  includeIf:
    activeProfileContainsAll:
      - mde
spec:
  label: 'Workflow Event Store Listener'
  autostart: true
  skipUpdateIfRunning: false
  startWorkflowAfterImport: false
  components:
    - name: Event Store KG Events
      type: "#Hume.Orchestra.DataSource.EventStore"
      config:
        pollFrequency: 3
        streamIdentifier: $(knowledgeGraph.uuid)
        clear_offset_repository: true
      resourceName: eventstore
      to:
        - Observer
    - name: Observer
      type: "#Hume.Orchestra.Monitor.Observer"