kind: Action
metadata:
  name: ab-profile-related-offences-chart
  knowledge-graph: SPINE
spec:
  label: ab-profile-related-offences-chart
  query: |-
    MATCH path = (n:Person WHERE elementId(n) = $person)
    ( (:Person)-[:RESOLVED_TO]->()<-[:RESOLVED_TO]-() ) {0,1}

    WITH collect([n in nodes(path) WHERE n:Person | n.id]) AS paths

    CALL(paths) {
      UNWIND paths AS path
      UNWIND path AS id
      RETURN collect(distinct id) AS ids}

    WITH ids

    MATCH (p:Person)-[:CHARGED_FOR]->(o)
      WHERE p.id IN ids

    WITH o.primaryType AS primaryType, count(distinct o) AS frequency
    WITH collect({`Primary Type`: primaryType, Frequency: frequency}) AS records

    RETURN records AS values, "arc" AS chartType,
      {
          theta: {field: "Frequency", type: "quantitative"},
          color: {field: "Primary Type", type: "nominal"}
      } AS options
  returnType: CHART
  scope: UTILITY
  inclusions: {}
  inputParameters:
  - name: person
    label: Person
    type: STRING
    multiselect: false
    list: false
    required: true
    forgetValue: true
  actionType: CYPHER
  canvasOptions:
    clearCanvas: false
    fitCanvas: false
  httpActionIncludeCanvasInPayload: false
