kind: Action
metadata:
  name: individual's-co-offenders-network
  knowledge-graph: SPINE
spec:
  label: Individual's Co-offenders network
  query: |-
    MATCH (n)
    WHERE elementId(n) IN $_selection.nodeElementIds
    MATCH path=(n)-[:CHARGED_FOR]->(offence)<-[:CHARGED_FOR]-(p:Person)
    RETURN path
  returnType: GRAPH
  scope: MULTISELECTION
  inclusions:
    labels:
    - Person
  actionType: CYPHER
  canvasOptions:
    clearCanvas: false
    fitCanvas: false
  httpActionIncludeCanvasInPayload: false
