kind: Action
metadata:
  name: offences-around-the-selected-location
  knowledge-graph: SPINE
spec:
  label: Offences around the selected location
  description: |-
    Displays Offences committed nearby the selected one, grouped by primary type.

    <br>

    **Selection:**

    *   **Offence**: the offence that serves as the center of this analysis.

    <br>

    **Parameters:**

    *   **Radius to consider** (in kms): Select the kilometres representing the radius of the selected area.
    *   **Return Type:** select the format of the results (TABLE or CHART).
  query: |
    MATCH (o:Offence)
      WHERE elementId(o) IN $_selection.nodeElementIds
      AND o.location IS NOT NULL
    WITH o, o.location AS center

    MATCH offences = (q:Offence)-[:CHARGED_FOR]-(offender)
      WHERE q.location IS NOT NULL
      AND point.distance(q.location, center)<= $radius * 1000
      AND q.primaryType IS NOT NULL

    WITH o, q
    WITH distinct q.primaryType AS primaryType, count(q) AS Frequency
    ORDER BY Frequency DESC
    WITH collect({Frequency: Frequency, `Primary Type`: primaryType}) AS records

    CALL (records) {
      WHEN $returnType = 'CHART'
        THEN {
          WITH records, "arc" AS chartType,
          {
            theta: {field: "Frequency", type: "quantitative"},
            color: {field: "Primary Type", type: "nominal"}
          } AS options
          RETURN //values, chartType, options
            { values: records, chartType: chartType, options: options } AS __content__
        }

      ELSE {
        RETURN records AS __content__
      }
    }
    RETURN __content__ , {returnType: $returnType} AS __metadata__
  returnType: DYNAMIC
  scope: LOCAL
  inclusions:
    labels:
    - Offence
  inputParameters:
  - name: radius
    label: Radius to consider (in kms)
    type: FLOAT
    multiselect: false
    list: false
    required: true
    forgetValue: false
  - name: returnType
    label: Return Type
    type: SELECT
    multiselect: false
    list: false
    required: false
    selectOptions:
    - value: CHART
      label: CHART
    - value: TABLE
      label: TABLE
    forgetValue: false
  actionType: CYPHER
  canvasOptions:
    clearCanvas: false
    fitCanvas: false
  httpActionIncludeCanvasInPayload: false
